// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crehxakoldqqzeoklklw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZWh4YWtvbGRxcXplb2tsa2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDM3NTgsImV4cCI6MjA2NTIxOTc1OH0.LEQMayz313rE0droUq1oy5N2QolY_eIRrBL957o9UNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);